//Dedicated to God the Father

//All Rights Reserved Christopher Topalian Copyright 2020-2021

//THIS IS THE DATA (CONTENT) that we are using for the Topalian Game Engine Video Navigator - YouTube Edition

//This File is Saved as TopalianDataBoxing.js

//We make sure to only use Single Quotes in the title, description, tag, words, etc.

//We do NOT use Double Quotes in the title, description, tag, words, etc.

//Double quotes end the strings, so we don't use them in our title, description, tag, words, etc.

let bdaBoxingComments =
[  
{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:04:20", endTime:"00:05:20", description:"shoulder excuse", words:"BDA cites the shoulder injury excuse. BDA attempts to excuse the excuse by citing the source of the report.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:04:44", endTime:"00:05:44", description:"funny", words:"Bucho claims that he found NO channels making excuses for Lomachenko. Bucho name calls any person making excuses for Lomachenko, as PSYCHOS. Bucho says there are a lot of PSYCHOS and redefines channels to mean: MAJOR Boxing Channels.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:06:48", endTime:"00:07:48", description:"shoulder excuse", words:"BDA cites the shoulder injury excuse. BDA attempts to excuse the excuse by citing the source of the report. BDA also attempts to excuse the excuse by claiming that the excuse had to be announced or else Lomachenko HATERS, would call Lomachenko a LIAR, for not citing the excuse.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:07:28", endTime:"00:08:28", description:"funny", words:"Bucho claims that Lomachenko almost STOPPED Teofimo. Bucho claims that his prediction was ALMOST correct, because, he claims, he previously stated, that Lomachenko was gonna stop the guy.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:07:40", endTime:"00:08:40", description:"size excuse", words:"Bucho claims that SIZE is why Lomachenko lost. Bucho claims that Teofimo being BIGGER is why Lomachenko lost.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:08:03", endTime:"00:09:03", description:"attacks person", words:"Bucho claims that people who disagree with his opinion do NOT know Sh#$ about boxing.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:08:11", endTime:"00:09:11", description:"funny", words:"BDA claims Teofimo Lopez was going to get overwhelmed in the 12th round.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:08:28", endTime:"00:09:28", description:"size excuse", words:"BDA claims that SIZE is why Lomachenko lost. BDA calls it the SIZE ADVANTAGE.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:08:45", endTime:"00:09:45", description:"funny", words:"Bucho gets upset at ScriptingColleges comment in the chat and instead of Responding to the content of the comment, Bucho instead attempts to define the comment as an EXCUSE. Bucho then tries the DISTRACTION FALLACY to another topic, instead of responding to the 40+ behind the head shots that Fury committed on Wilder, which is what ScriptingColleges comment speaks about. Bucho accuses ScriptingCollege of making many excuses, yet, it is Bucho who refuses, again, to talk about the 40+ behind the head shots that Fury landed on Wilder.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:09:30", endTime:"00:10:30", description:"funny", words:"Bucho asks ScriptingCollege to show him another channel or community of people that are making excuses for Lomachenko and claims there are none.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:10:15", endTime:"00:11:15", description:"shoulder excuse", words:"BDA claims it is the MANAGER or PROMOTER of Lomachenko, who TOLD THE SURGEON TO COME UP WITH THE SHOULDER INJURY NEWS. BDA claims he does NOT see Lomachenko doing that. BDA attempts to excuse the excuse by citing the source of the report. BDA claims it looks like an excuse if Lomachenko reports the shoulder injury, but is NOT an excuse if someone else reports it.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:10:43", endTime:"00:11:43", description:"shoulder excuse", words:"BDA ADMITS that the shoulder injury excuse is an excuse, BDA states that the shoulder injury excuse is a good excuse, because  the shoulder injury excuse was known prior to the fight. BDA claims that Lomachenko MIGHT HAVE BEEN INJURED before the match.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:14:13", endTime:"00:15:13", description:"attacks person", words:"BDA states that anyone who has the opinion that Lomachenko is not a good boxer are HATERS and HAVE NO STANDARDS whose opinions are inspired by HATE.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:20:24", endTime:"00:21:24", description:"shoulder excuse", words:"BDA agrees with the caller that Teofimo Lopez MAYBE knew about Lomachenkos shoulder injury PRIOR to the fight.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:22:23", endTime:"00:23:23", description:"shoulder excuse", words:"BDA cites shoulder injury excuse. BDA agrees that the shoulder injury is trying to rob credit from Teofimo, but then tries to justify the shoulder excuse by stating that it is a POSSIBILITY, because Lomachenko had talked about the shoulder injury in the past. BDA claims that a shoulder injury could effect the boxers ability, so that he is justified in bringing that shoulder excuse to the FORE FRONT.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:23:03", endTime:"00:24:03", description:"shoulder excuse", words:"BDA says ITS NOT THAT WE ARE TAKING CREDIT AWAY FROM HIM but it is something worth considering BDA says. BDA agrees with the claim that MAYBE Lomachenkos shoulder injury was why Lomachenko didnt throw many punches for the first 6 rounds. BDA says he finds NO fault in using the shoulder excuse.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:24:14", endTime:"00:25:14", description:"shoulder excuse", words:"BDA admits that the shoulder injury excuse is an excuse. BDA claims the excuse isnt bad, because Lomachenko told people about the shoulder injury in the past.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:07:50", endTime:"00:08:50", description:"shoulder excuse", words:"BDA cites the shoulder excuse again. Bucho claims people are wrong to call the shoulder excuse an excuse. Bucho attempts to defend the shoulder excuse with an implication that if Lomachenko doesnt think it is an excuse, then it must NOT be an excuse.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:28:05", endTime:"00:29:05", description:"shoulder excuse", words:"Recognize cites the news article about Lomachenkos shoulder injury excuse. Recognize says it was Lomachenkos MANAGER or his ADVISOR that he said that Lomachenko underwent surgery. Recognize cites that it is common for boxers to come into fights with injuries.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:30:07", endTime:"00:31:07", description:"promoter excuse", words:"Bucho asks Recognize if he is MAKING EXCUSES? Recognize answers, NO, he doesnt believe hes making excuses. Recognize claims that TOP RANK and ESPN wanted Teofimo to win the fight, which he states is because Teofimo is more marketable.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:31:50", endTime:"00:32:50", description:"judges excuse", words:"Bucho cites how hes seen so many fighters get ROBBED and asks if THIS FIGHT finally proves that there NO Eastern European agenda?", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:33:18", endTime:"00:34:18", description:"size excuse", words:"Recognize cites BIG STRONG ATHLETE excuse. Recognize claims that Teofimo has been studying Lomachenko for 2 years.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:34:42", endTime:"00:35:42", description:"size excuse", words:"Bucho claims the SIZE excuse. Bucho says the SIZE DIFFERENCE is something they knew that was gonna happen. Bucho claims that Lomachenko had a HANDICAP for being SMALLER than Teofimo.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:35:20", endTime:"00:36:20", description:"size excuse", words:"Bucho again cites the SIZE excuse. Bucho claims that SAYING BIGGER IS NOT AN EXCUSE, but instead, a REALITY. Bucho claims the SIZE EXCUSE is NOT an EXCUSE because he had heard other people say also that Teofimo looked BIGGER.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:35:50", endTime:"00:36:50", description:"size excuse", words:"Bucho says there is no eastern European agenda, and that Lomachenko should NOT move up to 147lbs, because Bucho thinks Lomachenko would lose and people who think differently from his opinion KNOW NOTHING about boxing. Bucho says Teofimo can go to 147lbs, but claims that Lomachenko would lose at 147lbs.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:38:06", endTime:"00:39:06", description:"size excuse", words:"Bucho cites the SIZE excuse. Bucho asks what would have happened if Lomachenko had stayed at 130lbs. Bucho asks, would he had lost at 130lbs, probably not, Bucho says.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:39:01", endTime:"00:40:01", description:"funny", words:"Bucho again claims that Teofimo was a little bit OVERWHELMED in the 12th round.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:43:34", endTime:"00:44:34", description:"shoulder excuse", words:"BDA cites the shoulder injury excuse and admits that Lomachenko was pumping his jab out without seeming to have injury.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:43:53", endTime:"00:44:53", description:"shoulder excuse", words:"BDA cites that he doesnt know the severity of the injury. Gonzalo claims the shoulder injury was severe to cause single digit output in first rounds. Gonzalo claims that in the first couple rounds, Teofimo hit Lomachenko in the shoulder, really really hard Gonzalo says, to which Pete immediately asks: HE TORE HE LABRUM? Pete asks again: He tore his Labrum with a shoulder shot? Pete exclaims that Teo got power. Pete repeats again: Teo tore Lomachenkos Labrum with a shoulder shot. Pete asks the panel: Is that what were saying, or no? Gonzalo summarizes, that maybe Lomachenko was hurt early in the fight.", name:"Gonzalo" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:44:38", endTime:"00:45:38", description:"shoulder excuse", words:"Recognize shoulder excuse. Recognize refers to Lomachenkos shoulder as his BAD SHOULDER. Recognize blames Teofimo for trying to HIT EVERYTHING and in doing so, that maybe Lomachenkos BAD shoulder was hurt worse. Recognize claims because Teofimo is BIGGER, Lomachenko might have hurt his shoulder trying to equal the BIGGER mans power. Recognize claims Lomachenko might have TORE his shoulder from being smaller than Teo.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:46:05", endTime:"00:47:05", description:"shoulder excuse", words:"Gonzalez with his shoulder excuse. Gonzalo exclaims that Shoulder injury are VERY easy to get and that even if it wasnt a punch hitting Lomachenkos shoulder, that maybe Lomachenko himself tore his own shoulder just by punching.", name:"Gonzalo" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:46:20", endTime:"00:47:20", description:"shoulder excuse", words:"BDA injury excuse. BDA claims that he himself, messes his own tendons up, when he tries to punch.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:52:46", endTime:"00:53:46", description:"size excuse", words:"Recognize SIZE excuse. Recognize says Teofimo fought BIG BECAUSE HE IS THE BIGGER GUY. Recognize claims his size excuse is NOT an excuse, but instead, a reason.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:53:26", endTime:"00:54:26", description:"size excuse", words:"Recognize claims that Tyson Fury won because he was Bigger than Wilder. Bucho agrees with Recognize, and says people should use that excuse, because Bucho thinks its a valid excuse.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:53:45", endTime:"00:54:45", description:"size excuse", words:"Bucho SIZE excuse. Bucho again states that he KNEW that Teofimo was BIGGER. Bucho claims that Lomachenko was HANDICAPPED by being so small. Recognize agrees with Buchos Size excuse.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:53:45", endTime:"00:54:45", description:"size excuse", words:"Bucho claims the SIZE EXCUSE. Bucho says that Teofimo is WAS TOO BIG and that hes moving up in weight. Bucho claims the SIZE EXCUSE is NOT an EXCUSE, but instead a REALITY. Bucho claims the size excuse isnt an excuse, since other people thought Teo was BIGGER too.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"00:55:28", endTime:"00:56:28", description:"size excuse", words:"BDA Size excuse. BDA attempts to define the SIZE EXCUSE as being a FACTOR, instead of an EXCUSE.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:02:05", endTime:"01:03:05", description:"mockery", words:"Bucho reads a comment immediately after Dee speaks, from APOLOGY, that attempts to devalue Dees CORRECT pick of Teofimo to Win, because Dee chose by knockout as the method of winning. Recognize agrees that Dees prediction was only partially right, in an attempt to devalue it. BDA laughs, and then Bucho reads another chat comment that says, No one said how Teofimo would win by decision.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:03:28", endTime:"01:04:28", description:"attacks person", words:"Dee commits name calling, by calling the opponent a DUMB A#$.", name:"Dee" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:10:47", endTime:"01:11:47", description:"size excuse", words:"BDA Size Excuse. BDA says it wasnt ONLY the SIZE Excuse, but also the MUSCLE excuse that people should consider.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:13:25", endTime:"01:14:25", description:"low blow excuse", words:"Precise Low blow excuse. Precise claims that A LOT OF THOSE BODY SHOTS WERE LOW BLOWS.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:14:07", endTime:"01:15:07", description:"judges excuse", words:"Precise claims the fight was a close one. Precise says he disagrees with all of the score judges. Precise says 7 to 5 Teo is JUST, but then says, draw, or 7 to 5 Lomachenko is good too. Precise claims that if Teofimo was scored 5 out of 7 it wouldnt have been a Robbery.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:14:40", endTime:"01:15:40", description:"judges excuse", words:"Precise claims that Lomachenko could have won 10 rounds and still NOT have won because of judge corruption. Precise admits out loud that Lomachenko did NOT WIN enough rounds to claim Robbery. Precise then claims that THEY were FIXING TO ROB THIS KID ANYWAYS.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:14:51", endTime:"01:15:51", description:"judges excuse", words:"Precise admits that Lomachenko clearly lost by NOT winning enough rounds, and then in the same breathe, claims that the judges planned a robbery either way. Precise claims that Lomachenko got jobbed. Precise claims that Lomachenko ABSOLUTELY got JOBBED. Precise claims that the fight was fixed by the judges and that Lomachenko could have only won with knockout", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:15:15", endTime:"01:16:15", description:"judges excuse", words:"Precise claims that Lomachenko took off the early rounds, because Lomachenko knew that the judges would try to rob him. Precise claims that Lomachenko knew about other robberies in the past, so HE KNEW WHAT TIME IT WAS Precise says. Precise NAME CALLS anyone who disagrees with him as people in DENIAL. Precise cites comments in the chat, of others who thought robbery would occur. Precise then admits, that he cant really claim that Lomachenko got robbed. Precise claims that the FIGHT COULD HAVE GONE EITHER WAY as a decision. Precise claims even if Teo won 10 rounds, that he still would have lost. Precise claims that they DID LOMA DIRTY and SET HIM UP.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:16:03", endTime:"01:17:03", description:"funny", words:"Precise says he only chose Lomachenko, because Lopez is a LIAR and had concealed his HIDDEN SKILL from him. Precise claims that if Lopez hadnt LIED about his skill, that he would have picked him as the winner. Precise claims again, that THEY DID Lomachenko DIRTY.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:16:10", endTime:"01:17:10", description:"attacks person", words:"Pete says, WELL THEN F@#$ YOU THEN, to Dee Jefferson, after Dee stated that there is NO JUSTIFICATION POSSIBLE for a score card of Lomachenko winning 7-5 as Precise had claimed earlier, (the profanity used by Pete is at (01:16:48 well then f@#$ you then.))", name:"Pete" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:17:42", endTime:"01:18:42", description:"attacks person", words:"Pete attempts ATTACK ON THE PERSON by saying, GET THESE TEOFIMO ZEROS IN HERE, in reference to the callers calling in, who support Teofimo Lopez.", name:"Pete" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:18:27", endTime:"01:19:27", description:"mockery", words:"Bucho asks the caller Brotherhood, what was his prediction? Brotherhood responds: Lomachenko to be knocked out in the 5th round. I picked the winner right, he states. BDA laughed mockingly (01:18:49) when Brotherhood said he picked the right winner. Brotherhood says he thinks Teofimo won 120 to 108, and the panel laughs at him.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:18:52", endTime:"01:19:52", description:"attacks person", words:"PETE calls the caller and others with the callers opinion, ZOMBIES. Teo fans are a bunch of Zombies.  Pete said IM TELLING YOU BRO,  THERES SOME ZOMBIES OUT HERE. TEO FANS ARE A BUNCH OF ZOMBIES BRO.", name:"Pete" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:19:03", endTime:"01:20:03", description:"attacks person", words:"Stu ATTACKS THE PERSON by calling them a CLOWN. Stu said: I WANT TO SAY MY POINT AND YOURE F@#$^&* INTERRUPTING ME FOR THIS CLOWN.", name:"Stuart" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:19:31", endTime:"01:20:31", description:"attacks person", words:"BDA attempts to discredit Brotherhoods correct pick by asking: SO YOU HAD LOPEZ WINNING 5TH ROUND KNOCKOUT, THAT DIDNT HAPPEN, WHAT ELSE DO YOU GOT? Earlier he had laughed at Brotherhood for his correct winner pick.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:19:43", endTime:"01:20:43", description:"attacks person", words:"Brotherhood attempts SELF PRAISE for his purported GENIUS, and Recognize attempts to discredit that praise by citing that Brotherhood claimed Tyson Fury lost the fight. Brotherhood says he called Charlo to Win, and he called Teofimo to Win, and the panel was wrong he says. Recognize says they all picked Charlo to win.", name:"Brotherhood" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:20:05", endTime:"01:21:05", description:"you do it too", words:"BDA says to the caller YOURE SAYING THAT PRECISE IS MAKING EXCUSES, BUT YOU MADE A S@#$ TON. YOU SAID WILDER GOT ROBBED, FURY HAD METAL, HEAD BUTTS, BEHIND THE HEAD SHOTS. Brotherhood says: WHY DOES EVERYONE WANT TO DEFLECT TOWARD WILDER, JUST BECAUSE LOMACHENKO GOT HIS ASS WOOPED?", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:20:35", endTime:"01:21:35", description:"mockery", words:"Pete said: GET OFF THE F@#$ ROBITUSSIN DUDE. WHAT 13 ROUNDS, YOU WANT TO GIVE HIM 13 ROUNDS? Recognize said that he is SO BORED RIGHT NOW. Bucho says, LOMACHENKO HATERS think X.", name:"Pete" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:20:50", endTime:"01:21:50", description:"mockery", words:"Recognize says he is bored right now man. BDA implies that Brotherhood is a HATER. Recognize says he is BORED again and that he does NOT want to talk with Brotherhood again. Recognize claims confirmation bias of the caller brotherhood and claims that the Brotherhood FINALLY got it right, because he always picks against Lomachenko. Recognize says, he finally got ONE right, good for him.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:22:10", endTime:"01:23:10", description:"attacks person", words:"Recognize attacks the person and admits his own confirmation bias: BROTHERHOOD IS SO PREDICTABLE AND BORING I ALREADY KNOW WHAT HES GONNA SAY.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:24:05", endTime:"01:25:05", description:"mockery", words:"Dee attempts the implication of insanity fallacy, by saying it is CRAZY to him, how anyone could pick Santa Cruz to win. The implication is that a person who thinks Santa Cruz can win is CRAZY.", name:"Dee" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:27:42", endTime:"01:28:42", description:"funny", words:"Pete says, F@#$ THAT. F@#$ THAT S#$T, As the caller Virtuoso, was saying, that the panel had to accept that Lomachenko lost and to stop making excuses for their pick, Petes response was a profane refusal to accept it.", name:"Pete" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:28:05", endTime:"01:29:05", description:"funny", words:"Recognize asks: Whats up Apology? Pete says, LIFE SUCKS. Apology laughs, Recognize says HES TERRIBLE MAN.", name:"Pete" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:28:12", endTime:"01:29:12", description:"shoulder excuse", words:"BDA cites the shoulder injury excuse again. BDA claims Lomachenkos TEAM mentioned the shoulder injury in the past and he asks WHAT DO YOU THINK ABOUT THAT, BECAUSE IT WAS MANAGEMENT AND THE DOCTOR THAT CAME OUT AND SAID THAT HE WAS INJURED. LOMACHENKO DIDNT SAY THAT. BDA attempted to imply again that because Lomachenko didnt make the excuse, that it is okay to mention the shoulder injury excuse again and again.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:28:12", endTime:"01:29:12", description:"shoulder excuse", words:"Recognize cites the shoulder injury excuse as common in boxing. Recognize asks why anyone would see the shoulder excuse as an excuse. Recognize says that injuries happen ALL the time.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:28:38", endTime:"01:29:38", description:"shoulder excuse", words:"Precise exclaims Come On Man, HE HAD A SURGERY, THEN POSTED IT TO INSTAGRAM. DID HE SAY, OH, THIS IS WHY I LOST THE FIGHT? NO, HE HAD A SURGERY AND HE MADE IT PUBLIC, WHICH IS WHAT MOST BOXERS DO ANYWAY. NOW IF SOMEONE RUNS WITH THAT AND SAYS THATS WHY HE LOST THE FIGHT, WELL, WE DONT KNOW. PEOPLE DONT SEEM TO UNDERSTAND WHAT AN EXCUSE IS. EXCUSE IS BULLS$^&* AND ITS DIFFERENT FROM A REASON.  A REASON IS A REASON AND AN EXCUSE IS AN EXCUSE. A REASON IS SOMETHING THAT EXISTS. AN EXCUSE IS SOMETHING THATS MADE UP. THATS THE ONLY DIFFERENCE. Precise ADMITS he NEVER saw the Instagram post about the Surgery (01:29:22), and then tries to REPORT on what the post said, based on what others told him. Precise says that the post does NOT say, that THIS IS WHY WE LOST THE FIGHT. SO HE JUST POSTED THAT HE HAD AN INJURY. OKAY? END OF STORY! Precise tries to claim his excuse isnt an excuse, even though, it is an excuse.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:29:36", endTime:"01:30:36", description:"shoulder excuse", words:"BDA INTERRUPTS DEE as Dee accuses Both Bucho and Precise  of trying to claim that the INJURY WAS DURING THE FIGHT. BDA says HOLD ON, HOLD ON, HOLD ON,  HOLD ON. Bucho talks over Dee and cites that the shoulder excuse is good since, Bucho claims, Lomachenko didnt announce it. Bucho claims the manager and the doctor released the excuse, so therefore its NOT an excuse. BDA SAYS: DEE, CAN YOU HEAR ME, I JUST WANT TO CLARIFY, THAT I DONT SEE LOMACHENKO POSTING THAT. ALL I SEE IS AN ARTICLE FROM THE DOCTOR AND THE  MANAGEMENT. LOMACHENKOS BEEN KEEPING QUIET ABOUT THAT. SO ITS NOT EVEN LOMACHENKO. Apology cuts in: BECAUSE HES A HUMBLE GUY. HES NOT GONNA MAKE EXCUSES LIKE THAT! BDA continues to say: ITS ALWAYS THE MANAGEMENT. DEE YOU WERE GONNA SAY SOMETHING?", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:31:07", endTime:"01:32:07", description:"promotion excuse", words:"Precise claims that Dee has NO proof for his claim ABOUT the rematch clause. Precise asks Dee: CAN YOU PROVE THAT LOMACHENKO SAID I DONT WANT A REMATCH CLAUSE? LIKE, WHERES THE EVIDENCE? BECAUSE BOB ARUM CAME OUT IN AN INTERVIEW AND SAID I DONT LIKE REMATCH CLAUSES. SO TO ME, IT SOUNDS LIKE BOB ARUM DID NOT WANT A REMATCH CLAUSE. IT HAD NOTHING TO DO WITH LOMACHENKO. AND AS WE FOUND OUT, TEOFIMO WAS THE A SIDE ANYWAYS. SO HOW IS LOMACHENKO, THE B SIDE, GONNA DICTATE TO THE A SIDE? LIKE HOW IS THAT? THATS NOT EVEN GONNA. Precise accuses Dee of making an unsubstantiated claim, and then Precise himself makes an unsubstantiated claim by stating that Lomachenko had nothing to do with the rematch clause.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:31:35", endTime:"01:32:35", description:"judges excuse", words:"Dee responds, with Vulgarity: Didnt Lomachenko make more money? How the (expletive) is Teofimo, didnt it, wasnt it RUMORS? This was another (expletive) rumor, that Lomachenko gave Teofimo some extra (expletive) money so Teofimo could make the fight. How the (expletive) does the A side get paid the least amount of money? What the (expletive) are we talking about? Bucho then responds and says: 119 to 109. To me thats just NOT going along with that whole A B side thing. 119 to 109, theres some (expletive) going on. (Expletive) going on.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:33:15", endTime:"01:34:15", description:"judges excuse", words:"Apology states that the A side can make less money than the B side. Apology claims A side isnt only about money, but about having the judges in the corner, Having everything go your way. Recognize says: Yep. Apology then continues: Even in a close fight, youll get the swing of things. And that was CLEARLY, THIS FIGHT WAS CLEARLY a FIGHT SET UP FOR LOMACHENKO TO LOSE. I was laughing half way through the fight, it was just so funny to me, how clearly THEY wanted Teo to win. But, Ill give Teo credit later.", name:"Apology" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:33:52", endTime:"01:34:52", description:"compubox excuse", words:"Apology asks: Did anyone give Teo the 8th round? BDA says he wont answer until he rewatches the fight. Recognize says he doesnt remember. Precise, No, I didnt. I didnt. Apology claims EVERYONE thought Lomachenko won clearly, or it was close-ish, but Lomachenko edged it right? Gonzalo says: I gave it to Teo, but if you gave it to Loma its fair. Precise says: Lomachenko out landed Teofimo 20 to 5 or something. Apology claims, guess what, Compubox had them EVEN, but I saw the other side chuckling, and I was like yep, I knew, I knew where this was going. A set up. It was set up.", name:"Apology" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:34:33", endTime:"01:35:33", description:"compubox excuse", words:"Apology says he was just laughing, and it happened multiple times, they put the compubox numbers on the screen, which I dont believe anyway. It would say Teo landed this much, when he CLEARLY didnt. It was just funny to me how it was SET UP but go head. BDA asks: Do you have the compubox numbers? Apology states: I have a screen shot of ONE round. Ill send it right now. BDA says: One round? I need the whole Apology says: Ill rewatch it and send it to you.", name:"Apology" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:37:05", endTime:"01:38:05", description:"judges excuse", words:"Recognize claims judge excuse: Recognize says: To Dee Jeffersons point on, HOW IS LOMACHENKO THE B SIDE, when HE was scheduled to make more money. And look I think a lot of times people look at the money aspect and thats the tell all of a GUY WHOS GETTING THE BENEFIT OF THE DOUBT IN THE SCORE CARDS. Recognize then accuses Oscar Delahoya of FIXING FIGHTS in VEGAS for Canelo Alvarez, as his proof that Lomachenko was the B side to Teofimo.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:38:47", endTime:"01:39:47", description:"judges excuse", words:"Recognize judges excuse. Recognize claims you can see there was some BULLSH#$. Recognize claims: Its NOT making excuses, when someone says, look, I BELIEVE Teofimo was the guy that THEY WANTED TO WIN. Theres a lot of upside. What, boxings NOT corrupt? Recognize then lists Teofimos marketable attributes as the reasons why he won.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:39:30", endTime:"01:40:30", description:"judges excuse", words:"BDA says: I have to add something to that, because people in the chatroom are saying that those are excuses. BDA goes onto say that Lopez did win, but even though the panel has repeatedly claimed CORRUPT JUDGES again and again, that it is NOT an excuse. BDA claims the panels constant discussion about the corrupt judges isnt an excuse.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:40:10", endTime:"01:41:10", description:"judges excuse", words:"BDA continue his judges excuse and claims that BOB ARUM CAN TWEEK THINGS HOWEVER HE WANTS, as BDA references a Luke Campbell fight in the past, OR MAYBE I SHOULDNT BE BLAMING BOB ARUM, he concludes. Recognize says that Bob Arum is a business man and he will make choices that benefit HIM and his promotion crew, and Teofimo being part of that.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:40:42", endTime:"01:41:42", description:"funny", words:"Precise attempts to pretend that his excuses are reasons instead of excuses. ITS ABUNDANTLY CLEAR PEOPLE DONT KNOW THE DIFFERENCE BETWEEN A REASON AND AN EXCUSE, AND IM NOT GONNA GET INTO WHAT THAT IS. IF THEY WANT TO SPEAK THE TRUTH THEYLL LEARN THAT ON THEIR OWN. Precise then continues to attempt to claim that Lomachenko was the B side, and that more money only occurs for the A side, when different promotional companies are involved. Precise claims that Lomachenko made more money because he worked longer and asked for more money, but that Lomachenko was still NOT the A side against Teofimo.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:41:40", endTime:"01:42:40", description:"judges excuse", words:"Precise goes through reasons on why he imagines Teofimo to be the A side and how Top Rank set Teofimo up to win and how Top Rank wanted Lomachenko to lose. Precise said: IT WAS CLEAR LISTENING TO TIMOTHY BRADLEY, CALLING SHOTS THAT NEVER LANDED. IT WAS CLEAR LISTENING TO THE COMMENTATING TEAM. IT WAS CLEAR LOOKING AT THOSE SCORE CARDS. IT WAS CLEAR LOOKING AT THE COMPUBOX VERSUS WHAT ACTUALLY HAPPENED IN THE RING. IT WAS CLEAR THAT THEY WANTED LOMACHENKO TO LOSE.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:42:23", endTime:"01:43:23", description:"judges excuse", words:"Precise accuses Lomachenko of NOT being able to win.  Precise claims it was NOT possible for Lomachenko to win because of the judge excuse. BDA agrees with Precise and says: RIGHT.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:43:36", endTime:"01:44:36", description:"funny", words:"Dee makes a Summary of the excuses the panel used in the show. *Excuses the Panel used in this show: *A Side JUDGE CORRUPTION *Setting Lomachenko UP to lose. *Shoulder Injury. *Lomachenko did NOT do anything. Bucho interrupts: Are you saying the shoulder injury was… Apology interrupts: IS HE DONE? Can I Respond?", name:"Dee" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:44:14", endTime:"01:45:14", description:"shoulder excuse", words:"Bucho tries to pretend that REPEATEDLY talking about the shoulder injury isnt an excuse. Bucho says: NO BODY MENTIONED HERE THAT THE SHOULDER INJURY WAS AN EXCUSE. SO IM SURE YOU WERE TALKING ABOUT OVER ALL RIGHT? DEE?", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:44:40", endTime:"01:45:40", description:"funny", words:"Bucho claims that NO one on His channel claimed a Robbery. But, on this very show, Precise claimed that he thinks that Lomachneko was SET UP TO LOSE by from the very beginning, by Top Rank, the judges, and the announcers and that it was NOT possible for Lomachenko to win, no matter what Lomachenko did that night against Teofimio and funny enough, later in the show, Precise says out loud, that he thinks that this fight is a ROBBERY. Bucho claims there are NO other channels like the ldbc fans channels, whom Bucho claims in the past, are biased, in what he states are 7 videos he made showing ldbc video clips of what Bucho accuses as being Excuses.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:46:30", endTime:"01:47:30", description:"judges excuse", words:"Apology accuses Dee of not addressing his should injury excuse and A side excuse. Apology claims Dee didnt address how the score cards were CLEARLY WIDE. Apology claims compubox, and the commentators, minus Andrea ward, were PRO TEOFIMO. Apology Accuses Teofimo of at least 8 low blows. Apology claims CHEATING by Teofimo for the low blows. Apology COMPLAINS that YOU SHOULDNT BE ABLE TO GET AWAY WITH THAT (expletive) SO I WANT TO KNOW WHY YOURE NOT ADDRESSING ANY OF THOSE POINTS? YOURE JUST GOING OFF THINGS THAT CAN EASILY BE DEBUNKED BUT YOUR NOT SEEING THE CLEARER PICTURE. Apology claims that since Dee doesnt Agree with his opinion, that Dee DOES NOT SEE CLEARLY. Apology claims Dees statements can easily be debunked, yet, he does NOT debunk any of them. Apology tried to pretend that Dee didnt address the panel, but Dee in fact did.", name:"Apology" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:47:46", endTime:"01:48:46", description:"attacks person", words:"Apology pretends to be RIGHT and does not believe Dee can be right. Apology tries to pretend that that his opinion is a fact. Apology accuses Dee of Not agreeing with Facts, Because Dee does not agree with Apologys opinion of A Side or Compubox excuses and Apology continues and asks: HOW IS THAT NOT CORRUPTION? Dee asks if he counted. Apology says he WILL count them. Apology did NOT count the punches, yet tried to tell the audience that compubox was wrong. Apology says: SO YOU AGREE WITH ME THAT TEOFIMO WAS THE A SIDE THEN? Dee says: I SAID I ADDRESSED IT Apology says: SO YOU DONT AGREE WITH FACTS THEN? SO YOU DONT AGREE WITH FACTS THEN? YOU DONT AGREE WITH FACTS? OKAY FINE, THATS UP TO YOU.", name:"Apology" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:49:03", endTime:"01:50:03", description:"judges excuse", words:"Apology continues to claim that his opinion is FACT. Apology already admitted to that he NEVER COUNTED THE NUMBER OF PUNCHES. Apology then insults Dee and says he doesnt know how to score boxing, since Dee does NOT agree with Apologys assumption of compubox bias, which Apology claims exists for Teofimo. Apology repeats over and over that DEE Does NOT know how to score fights. Apology tried to replace his lack of count evidence with attacks on Dees boxing knowledge.", name:"Apology" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:50:00", endTime:"01:51:00", description:"attacks person", words:"Recognize tries to blame Dee for being insulting, even though it was Apology who repeatedly stated that Dee doesnt know how to score boxing. Recognize is being UNJUST and siding against DEE in spite of evidence showing it was Apology who was being disrespectful with continual comments that Dee doesnt know how to score boxing.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:50:55", endTime:"01:51:55", description:"compubox excuse", words:"Precise asks Dee if the 12th round had 50 punches landed by Teofimo.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:51:55", endTime:"01:52:55", description:"funny", words:"Gonzalo states that the first 6 to 7 rounds, Lomachenko landed in single digits, to his eyes.", name:"Gonzalo" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:53:04", endTime:"01:54:04", description:"compubox excuse", words:"Precise cites compubox stats of 47 punches landed in round 12 by Teofimo.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:54:04", endTime:"01:55:04", description:"attacks person", words:"Precise claims they should move onto another topic, because he claims that Dee cant ANSWER a simple question. Precise claims that he is trying to have a LOGICAL conversation, asking logical questions, looking for GOOD ANSWERS but that it is IMPOSSIBLE to do that WITH DEE.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:54:20", endTime:"01:55:20", description:"commentator excuse", words:"Bucho thought that Andre Ward and Timothy Bradley were very PRO Teofimo. Recognize says: But he had it 6 to 6. Bucho says: Andre Ward has ALWAYS BEEN JEALOUS of Lomachenko Recognize says again: Andre had it 6 to 6.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:55:29", endTime:"01:56:29", description:"judges excuse", words:"Recognize judge excuse. Recognize asks: How can you not see that the benefit of the doubt was given to Teofimo. Teofimo who is the LESS POPULAR FIGHTER. This happens in boxing man, Recognize claimed.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:56:50", endTime:"01:57:50", description:"judges excuse", words:"BDA says hes doing what he does as boxing autists, and they are getting very deep into everything about the fight. The bottom line, like Bucho said, it was about comparing the EXCUSES that some fighters make, or some fans of certain fighter make and then others. This discussing that the fact that the score cards were wide, I dont see how thats making excuses for Lomachenko, because everyone here admits or more or less admits that Lomachenko didnt win that fight.", name:"BDA" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:57:20", endTime:"01:58:20", description:"funny", words:"Bucho reads the chat, and says, these fans are worse than the Wilder Fans. Bucho claims theres no way. Did you even hear the Wilder excuses? The Gloves were tampered with, he had a metal object in the gloves to the LED lights that affected Wilders vision, I mean, be honest man. Get the F@#$ off this channel.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:57:24", endTime:"01:58:24", description:"judges excuse", words:"Precise claims the audience wants the panel to admit that Lomachenko is over hyped. Precise says he does NOT believe Lomachenko is over hyped. Pete agrees and says Yeah F@#$ that. Precise claims that the fight was Controversial for many reasons. Precise claims that the fight was controversial because he states that people are disagreeing as to the outcome of the fight. Precise next cites the scorecards again. Precise then says: Even if the judges said the right guy won lets say, Its still controversial because it is.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:58:38", endTime:"01:59:38", description:"funny", words:"Precise claims there was NOTHING Controversial about Tyson Fury wooping Deontay Wilders A#$, so they had to invent controversy. Precise FAILS TO MENTION THE 40+ BEHIND THE HEAD SHOTS THAT FURY HIT WILDER WITH. Precise FAILS to acknowledge that BEHIND THE HEAD SHOTS are ILLEGAL and 40+ behind the head shots should have resulted in the disqualification of Tyson Fury for cheating and that behind the head hits adversely affect a boxers abilities in the ring.", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:58:47", endTime:"01:59:47", description:"judges excuse", words:"Precise says: The fights arent even comparable. Recognize agrees. Precise says: JUST BECAUSE SOME OF US REJECT THE MAIN STREAM  NARRATIVE AND THE C#$% SUCKING OF TIMOTHY BRADLEY AND THE TOP RANK TEAM OF TEOFIMO LOPEZ, THAT DOESNT MEAN WE DONT THINK HE WON THE FIGHT. YOU KNOW WHAT I MEAN? WERE JUST POINTING OUT, AH. And to me, in my eyes THAT JUSTIFIES Lomachenkos Gameplan in this fight. Because, it DIDNT LOOK like he could WIN A DECISION and he fought like he couldnt. Like he didnt give a F@#$ about WINNING ROUNDS, he just wanted to KNOCK HIM OUT. Thats how he fought, and it makes perfect sense in retrospect. Thats all Im saying. Precise exclaimed", name:"Precise" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"01:59:50", endTime:"02:00:50", description:"funny", words:"Recognize points out Dee Jeffersons use of Curse words. Recognize says that Dee is quick to use curse words. BDA correctly interrupts Recognize and says NO talking about someone when they are NOT here. BDA then correctly corrects Apology for his earlier insult to Dee, which was an attack on the person, when Apology had repeatedly said to Dee that Dee didnt know how to score boxing.", name:"Recognize" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"02:02:08", endTime:"02:03:08", description:"judges excuse", words:"The caller Kevin claims they Rob foreign fighters in America. Bucho says: I agree with you.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"02:02:58", endTime:"02:03:58", description:"judges excuse", words:"Bucho says, if it had been a closer fight, the score card would have made a big difference. That judge would have made a difference. Teofimo WAS GOING TO WIN NO MATTER WHAT. Precise says: She did make a difference, thats the point I was trying to make. I dont think you guys are understanding. Im not gonna repeat it. Im gonna take it some where else.", name:"Bucho" },

{ title:"Lomachenko fans making excuses like the LDBC/Wilder fanboys?", date:"10/21/2020 12:00 AM", url:"https://www.youtube.com/embed/JZpvDUeUU24", tag:"youtubeVideo", startTime:"02:03:45", endTime:"02:04:45", description:"judges excuse", words:"Precise claims: If Lomachenko understood, and to me it looked like he did understand, that he CANNOT WIN ON THE CARDS, that CHANGES HIS GAME PLAN.  Precise continues and says: His number of choices is all of a sudden limited. He cant just go in and box the guy because hes not gonna get the decision. He has to change his entire game plan. He has to take tremendous risks trying to knock him out and only in the last few rounds of the fight, thats not a level playing field. Of course it was a ROBBERY, of course it was. We can sit here and like rationalize, well technically he didnt win and so so it wasnt a Robbery. Man, they were gonna ROB HIM NO MATTER WHAT!", name:"Precise"}
];